### ISSUE TITLE
generated .en file in language directory missing

### ISSUE THREAD

**Issue by sr258** [jsxgraph/H5P.JSXGraph#1]
I'd like to add this library to https://translate-h5p.tk but for this there must be a .en.json file in the language directory. It contains the localizable strings from semantics.json in English. Weblate uses it as a base for its translations into new languages. Can you provide one? It can be (partly) auto-generated with the h5p cli tool.

**Comment by alfredwassermann** [comment]
OK, done.

**Comment by sr258** [comment]
The file should be named .en (mark the dot), as it's generated and not supposed to be used as an actual locale.

**Comment by alfredwassermann** [comment]
Done!

**Comment by sr258** [comment]
Sorry, there was a misunderstanding, it's  ".en.json" not just ".en". The language code is ".en" and it's still a JSON file. There reason for this is that .en.json is not picked up as "English" but the semantics.json strings are used for English. Still tools like Weblate need a base file, so there's the convention to use ".en" as an "pseudo" language code.

**Comment by alfredwassermann** [comment]
Done. Slowly, the process converges... Sorry for my ignorance.
